# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4bbe5f132788135489f8cb1baa9739a4d2954a13518de616dc4fe3d8cb5bc4c4057b1c197978395c4c67ea97a1eb169a8ce628a2f60c2a5cfb78ad76c502bf6

test:
  secret_key_base: b3608b4d385b3332f9899cac5d2ba9fd88cf50b522af6b0db8e3548f4295126a215cba140850bd4bf4b92e025236da045d741d5ddb6eb484a01d1d57e0ec4169

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
